export const INTEREST_CATEGORIES: { name: string; options: string[] }[] = [
  { name: "Creativity", options: ["Photography", "Painting", "Drawing & Sketching", "Pottery & Ceramics", "Creative Writing", "Poetry", "Filmmaking", "Graphic Design", "Fashion Design", "Jewelry Making", "Woodworking", "Calligraphy", "Sculpting", "Knitting & Crochet", "Scrapbooking", "Interior Design", "Animation", "Songwriting", "DIY & Crafts", "Upcycling & Repurposing"] },
  { name: "Fan Favorites", options: ["Marvel & DC", "Star Wars", "Harry Potter", "Anime & Manga", "K-Pop", "Taylor Swift", "True Crime", "Reality TV", "Comic Books", "Video Game Lore", "Cosplay", "Fantasy Novels", "Sci-Fi", "Broadway & Musicals", "Stand-Up Comedy", "Pro Wrestling", "Disney", "Horror Movies", "Pop Culture Trivia", "Cult Classics"] },
  { name: "Food & Drink", options: ["Cooking", "Baking", "Wine Tasting", "Craft Beer", "Coffee & Espresso", "Cocktail Making", "Food Trucks", "Sushi", "BBQ & Grilling", "Vegan Cooking", "Farmers Markets", "Fine Dining", "Home Brewing", "Tea Culture", "Cheese Boards", "Street Food", "Meal Prepping", "Whiskey & Spirits", "Brunch Culture", "Chocolate & Desserts"] },
  { name: "Gaming", options: ["Console Gaming", "PC Gaming", "Mobile Gaming", "Board Games", "Card Games", "Tabletop RPGs", "Esports", "Retro Gaming", "VR Gaming", "Puzzle Games", "Strategy Games", "Chess", "Poker", "Dungeons & Dragons", "Speedrunning", "Game Streaming", "Fantasy Sports", "Arcade Games", "Fighting Games", "Open-World Games"] },
  { name: "Going Out", options: ["Live Music Shows", "Nightclubs", "Bar Hopping", "Karaoke", "Comedy Clubs", "Dancing", "Concerts", "Music Festivals", "Rooftop Bars", "Wine Bars", "Speakeasies", "Trivia Nights", "Late-Night Diners", "Happy Hour", "Pop-Up Events", "Art Walks", "Food & Wine Festivals", "Drag Shows", "Silent Discos", "Open Mic Nights"] },
  { name: "Music", options: ["Live Concerts", "Vinyl Collecting", "Playing Guitar", "Playing Piano", "Playing Drums", "Singing", "DJing", "Music Production", "Hip-Hop", "Indie Music", "Jazz", "Classical Music", "R&B & Soul", "Country Music", "Electronic & EDM", "Rock Music", "Musical Theater", "Discovering New Artists", "Music History", "Band Practice"] },
  { name: "Outdoors & Adventure", options: ["Hiking", "Camping", "Backpacking", "Rock Climbing", "Kayaking", "Canoeing", "Fishing", "Hunting", "Mountain Biking", "Trail Running", "Surfing", "Skiing", "Snowboarding", "Scuba Diving", "Sailing", "Birdwatching", "Gardening", "National Parks", "Road Trips", "Stargazing"] },
  { name: "Sports & Fitness", options: ["Running", "Weightlifting", "Yoga", "Pilates", "CrossFit", "Basketball", "Football", "Soccer", "Baseball", "Tennis", "Golf", "Swimming", "Cycling", "Martial Arts", "Boxing", "Volleyball", "Skateboarding", "Rollerblading", "Marathon Training", "Spin Class"] },
  { name: "Staying In", options: ["Movie Nights", "Reading", "Puzzles & Crosswords", "Cooking at Home", "Journaling", "Listening to Podcasts", "Napping", "Home Organizing", "Video Calls with Friends", "Binge-Watching Shows", "Card Games at Home", "Home Improvement Projects", "Plant Care", "Cozy Nights In", "Ordering Takeout", "Sunday Reset Routines", "Building LEGO Sets", "Coloring Books", "Sudoku", "Solo Coffee Mornings"] },
  { name: "TV & Movies", options: ["Documentaries", "Rom-Coms", "Action Movies", "Drama Series", "Sitcoms", "Foreign Films", "Award Shows", "Crime Dramas", "Late-Night Talk Shows", "Film Festivals", "Classic Movies", "Cult Films", "Movie Trivia", "Streaming Marathons", "Indie Films", "Animated Films", "Behind-the-Scenes Content", "Film Analysis", "Movie Soundtracks", "Mockumentaries"] },
  { name: "Values & Causes", options: ["Volunteering", "Environmental Activism", "Animal Rescue", "Social Justice", "Mental Health Awareness", "Community Organizing", "Political Activism", "Sustainability", "Feminism", "LGBTQ+ Advocacy", "Racial Equity", "Voting & Civic Engagement", "Charity Fundraising", "Mentoring", "Faith & Spirituality", "Minimalism", "Ethical Consumption", "Disability Advocacy", "Homelessness Outreach", "Climate Action"] },
  { name: "Wellness & Lifestyle", options: ["Meditation", "Breathwork", "Therapy & Self-Growth", "Skincare", "Sleep Optimization", "Mindfulness", "Nutrition", "Sober Living", "Astrology", "Tarot", "Manifestation", "Cold Plunges", "Spa Days", "Life Coaching", "Personal Development Books", "Herbal Remedies", "Digital Detoxing", "Slow Living", "Work-Life Balance", "Self-Care Routines"] },
];

export const MIN_INTERESTS = 15;
export const MIN_BIO_WORDS = 100;
